# Generated by Django 3.2.4 on 2021-07-25 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projects',
            options={'verbose_name': '项目表', 'verbose_name_plural': '项目表'},
        ),
    ]
